<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../version.xml" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Api" Version="1.18.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.QrCode" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Turnierplan.Dal\Turnierplan.Dal.csproj" />
    <ProjectReference Include="..\Turnierplan.ImageStorage\Turnierplan.ImageStorage.csproj" />
    <ProjectReference Include="..\Turnierplan.Localization\Turnierplan.Localization.csproj" />
  </ItemGroup>
</Project>
