using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Turnierplan.Dal.Migrations
{
    /// <inheritdoc />
    public partial class Rename_TournamentPlanner : Migration
    {
        /*
         * This migration was created manually by combining separate migrations!
         *
         * Migration 1: Renames the "PlanningRealm" columns and indices to "TournamentPlanner"
         * Migration 2: Renames the "PlanningRealm" table to "TournamentPlanner" - becuase the table name is included in the index names, this also re-creates all relevant indices
         * Migration 3: Renames the primary key sequence - this was not generated by EF, rather it was added manually
         *
         * After combining the migration code, several occurrences of an index being created by migration 1 being
         * deleted immediately after by migration 2 were removed. Those occurrances are kept with comments.
         *
         * It had to be done this way, becuase if all properties and classes are renamed in the domain model at once, EF would
         * no longer correctly detect the renames and would rather drop the existing table and create everything new from scratch.
         *
         * Further note: PostgreSQL 18 introduces named NOT NULL constraints. We do not make an effort to rename those constraints
         * because turnierplan.NET does not require a specific PostgreSQL version. Please refer to the PostgreSQL 18 release notes:
         *  -> https://www.postgresql.org/docs/release/18.0/#:~:text=names%20to%20be%20specified%20for%20NOT%20NULL%20constraint
         */

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // --- Start of Migration 1 ---

            migrationBuilder.DropForeignKey(
                name: "FK_Applications_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "Applications");

            migrationBuilder.DropForeignKey(
                name: "FK_IAM_PlanningRealm_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "IAM_PlanningRealm");

            migrationBuilder.DropForeignKey(
                name: "FK_InvitationLinks_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "InvitationLinks");

            migrationBuilder.DropForeignKey(
                name: "FK_Labels_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "Labels");

            migrationBuilder.DropForeignKey(
                name: "FK_TournamentClasses_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "TournamentClasses");

            migrationBuilder.RenameColumn(
                name: "PlanningRealmId",
                schema: "turnierplan",
                table: "TournamentClasses",
                newName: "TournamentPlannerId");

            migrationBuilder.RenameIndex(
                name: "IX_TournamentClasses_PlanningRealmId",
                schema: "turnierplan",
                table: "TournamentClasses",
                newName: "IX_TournamentClasses_TournamentPlannerId");

            migrationBuilder.RenameColumn(
                name: "PlanningRealmId",
                schema: "turnierplan",
                table: "Labels",
                newName: "TournamentPlannerId");

            migrationBuilder.RenameIndex(
                name: "IX_Labels_PlanningRealmId",
                schema: "turnierplan",
                table: "Labels",
                newName: "IX_Labels_TournamentPlannerId");

            migrationBuilder.RenameColumn(
                name: "PlanningRealmId",
                schema: "turnierplan",
                table: "InvitationLinks",
                newName: "TournamentPlannerId");

            migrationBuilder.RenameIndex(
                name: "IX_InvitationLinks_PlanningRealmId",
                schema: "turnierplan",
                table: "InvitationLinks",
                newName: "IX_InvitationLinks_TournamentPlannerId");

            migrationBuilder.RenameColumn(
                name: "PlanningRealmId",
                schema: "turnierplan",
                table: "IAM_PlanningRealm",
                newName: "TournamentPlannerId");

            migrationBuilder.RenameIndex(
                name: "IX_IAM_PlanningRealm_PlanningRealmId",
                schema: "turnierplan",
                table: "IAM_PlanningRealm",
                newName: "IX_IAM_PlanningRealm_TournamentPlannerId");

            migrationBuilder.RenameColumn(
                name: "PlanningRealmId",
                schema: "turnierplan",
                table: "Applications",
                newName: "TournamentPlannerId");

            migrationBuilder.RenameIndex(
                name: "IX_Applications_PlanningRealmId",
                schema: "turnierplan",
                table: "Applications",
                newName: "IX_Applications_TournamentPlannerId");

            // would have added 'FK_Applications_PlanningRealms_TournamentPlannerId'
            // would have added 'FK_IAM_PlanningRealm_PlanningRealms_TournamentPlannerId'
            // would have added 'FK_InvitationLinks_PlanningRealms_TournamentPlannerId'
            // would have added 'FK_Labels_PlanningRealms_TournamentPlannerId'
            // would have added 'FK_TournamentClasses_PlanningRealms_TournamentPlannerId'

            // --- Start of Migration 2 ---

            // would have dropped 'FK_Applications_PlanningRealms_TournamentPlannerId'
            // would have dropped 'FK_IAM_PlanningRealm_PlanningRealms_TournamentPlannerId'
            // would have dropped 'FK_InvitationLinks_PlanningRealms_TournamentPlannerId'
            // would have dropped 'FK_Labels_PlanningRealms_TournamentPlannerId'

            migrationBuilder.DropForeignKey(
                name: "FK_PlanningRealms_Organizations_OrganizationId",
                schema: "turnierplan",
                table: "PlanningRealms");

            // would have dropped 'FK_TournamentClasses_PlanningRealms_TournamentPlannerId'

            migrationBuilder.DropPrimaryKey(
                name: "PK_PlanningRealms",
                schema: "turnierplan",
                table: "PlanningRealms");

            migrationBuilder.DropPrimaryKey(
                name: "PK_IAM_PlanningRealm",
                schema: "turnierplan",
                table: "IAM_PlanningRealm");

            migrationBuilder.RenameTable(
                name: "PlanningRealms",
                schema: "turnierplan",
                newName: "TournamentPlanners",
                newSchema: "turnierplan");

            migrationBuilder.RenameTable(
                name: "IAM_PlanningRealm",
                schema: "turnierplan",
                newName: "IAM_TournamentPlanner",
                newSchema: "turnierplan");

            migrationBuilder.RenameIndex(
                name: "IX_PlanningRealms_PublicId",
                schema: "turnierplan",
                table: "TournamentPlanners",
                newName: "IX_TournamentPlanners_PublicId");

            migrationBuilder.RenameIndex(
                name: "IX_PlanningRealms_OrganizationId",
                schema: "turnierplan",
                table: "TournamentPlanners",
                newName: "IX_TournamentPlanners_OrganizationId");

            migrationBuilder.RenameIndex(
                name: "IX_IAM_PlanningRealm_TournamentPlannerId",
                schema: "turnierplan",
                table: "IAM_TournamentPlanner",
                newName: "IX_IAM_TournamentPlanner_TournamentPlannerId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_TournamentPlanners",
                schema: "turnierplan",
                table: "TournamentPlanners",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_IAM_TournamentPlanner",
                schema: "turnierplan",
                table: "IAM_TournamentPlanner",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Applications_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "Applications",
                column: "TournamentPlannerId",
                principalSchema: "turnierplan",
                principalTable: "TournamentPlanners",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_IAM_TournamentPlanner_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "IAM_TournamentPlanner",
                column: "TournamentPlannerId",
                principalSchema: "turnierplan",
                principalTable: "TournamentPlanners",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_InvitationLinks_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "InvitationLinks",
                column: "TournamentPlannerId",
                principalSchema: "turnierplan",
                principalTable: "TournamentPlanners",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Labels_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "Labels",
                column: "TournamentPlannerId",
                principalSchema: "turnierplan",
                principalTable: "TournamentPlanners",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TournamentClasses_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "TournamentClasses",
                column: "TournamentPlannerId",
                principalSchema: "turnierplan",
                principalTable: "TournamentPlanners",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TournamentPlanners_Organizations_OrganizationId",
                schema: "turnierplan",
                table: "TournamentPlanners",
                column: "OrganizationId",
                principalSchema: "turnierplan",
                principalTable: "Organizations",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            // --- Start of Migration 3 ---

            migrationBuilder.RenameSequence(
                name: "PlanningRealms_Id_seq",
                schema: "turnierplan",
                newName: "TournamentPlanners_Id_seq");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // --- Start of Migration 3 ---

            migrationBuilder.RenameSequence(
                name: "TournamentPlanners_Id_seq",
                schema: "turnierplan",
                newName: "PlanningRealms_Id_seq");

            // --- Start of Migration 2 ---

            migrationBuilder.DropForeignKey(
                name: "FK_Applications_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "Applications");

            migrationBuilder.DropForeignKey(
                name: "FK_IAM_TournamentPlanner_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "IAM_TournamentPlanner");

            migrationBuilder.DropForeignKey(
                name: "FK_InvitationLinks_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "InvitationLinks");

            migrationBuilder.DropForeignKey(
                name: "FK_Labels_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "Labels");

            migrationBuilder.DropForeignKey(
                name: "FK_TournamentClasses_TournamentPlanners_TournamentPlannerId",
                schema: "turnierplan",
                table: "TournamentClasses");

            migrationBuilder.DropForeignKey(
                name: "FK_TournamentPlanners_Organizations_OrganizationId",
                schema: "turnierplan",
                table: "TournamentPlanners");

            migrationBuilder.DropPrimaryKey(
                name: "PK_TournamentPlanners",
                schema: "turnierplan",
                table: "TournamentPlanners");

            migrationBuilder.DropPrimaryKey(
                name: "PK_IAM_TournamentPlanner",
                schema: "turnierplan",
                table: "IAM_TournamentPlanner");

            migrationBuilder.RenameTable(
                name: "TournamentPlanners",
                schema: "turnierplan",
                newName: "PlanningRealms",
                newSchema: "turnierplan");

            migrationBuilder.RenameTable(
                name: "IAM_TournamentPlanner",
                schema: "turnierplan",
                newName: "IAM_PlanningRealm",
                newSchema: "turnierplan");

            migrationBuilder.RenameIndex(
                name: "IX_TournamentPlanners_PublicId",
                schema: "turnierplan",
                table: "PlanningRealms",
                newName: "IX_PlanningRealms_PublicId");

            migrationBuilder.RenameIndex(
                name: "IX_TournamentPlanners_OrganizationId",
                schema: "turnierplan",
                table: "PlanningRealms",
                newName: "IX_PlanningRealms_OrganizationId");

            migrationBuilder.RenameIndex(
                name: "IX_IAM_TournamentPlanner_TournamentPlannerId",
                schema: "turnierplan",
                table: "IAM_PlanningRealm",
                newName: "IX_IAM_PlanningRealm_TournamentPlannerId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_PlanningRealms",
                schema: "turnierplan",
                table: "PlanningRealms",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_IAM_PlanningRealm",
                schema: "turnierplan",
                table: "IAM_PlanningRealm",
                column: "Id");

            // would have added 'FK_Applications_PlanningRealms_TournamentPlannerId'
            // would have added 'FK_IAM_PlanningRealm_PlanningRealms_TournamentPlannerId'
            // would have added 'FK_InvitationLinks_PlanningRealms_TournamentPlannerId'
            // would have added 'FK_Labels_PlanningRealms_TournamentPlannerId'

            migrationBuilder.AddForeignKey(
                name: "FK_PlanningRealms_Organizations_OrganizationId",
                schema: "turnierplan",
                table: "PlanningRealms",
                column: "OrganizationId",
                principalSchema: "turnierplan",
                principalTable: "Organizations",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            // would have added 'FK_TournamentClasses_PlanningRealms_TournamentPlannerId'

            // --- Start of Migration 1 ---

            // would have dropped 'FK_Applications_PlanningRealms_TournamentPlannerId'
            // would have dropped 'FK_IAM_PlanningRealm_PlanningRealms_TournamentPlannerId'
            // would have dropped 'FK_InvitationLinks_PlanningRealms_TournamentPlannerId'
            // would have dropped 'FK_Labels_PlanningRealms_TournamentPlannerId'
            // would have dropped 'FK_TournamentClasses_PlanningRealms_TournamentPlannerId'

            migrationBuilder.RenameColumn(
                name: "TournamentPlannerId",
                schema: "turnierplan",
                table: "TournamentClasses",
                newName: "PlanningRealmId");

            migrationBuilder.RenameIndex(
                name: "IX_TournamentClasses_TournamentPlannerId",
                schema: "turnierplan",
                table: "TournamentClasses",
                newName: "IX_TournamentClasses_PlanningRealmId");

            migrationBuilder.RenameColumn(
                name: "TournamentPlannerId",
                schema: "turnierplan",
                table: "Labels",
                newName: "PlanningRealmId");

            migrationBuilder.RenameIndex(
                name: "IX_Labels_TournamentPlannerId",
                schema: "turnierplan",
                table: "Labels",
                newName: "IX_Labels_PlanningRealmId");

            migrationBuilder.RenameColumn(
                name: "TournamentPlannerId",
                schema: "turnierplan",
                table: "InvitationLinks",
                newName: "PlanningRealmId");

            migrationBuilder.RenameIndex(
                name: "IX_InvitationLinks_TournamentPlannerId",
                schema: "turnierplan",
                table: "InvitationLinks",
                newName: "IX_InvitationLinks_PlanningRealmId");

            migrationBuilder.RenameColumn(
                name: "TournamentPlannerId",
                schema: "turnierplan",
                table: "IAM_PlanningRealm",
                newName: "PlanningRealmId");

            migrationBuilder.RenameIndex(
                name: "IX_IAM_PlanningRealm_TournamentPlannerId",
                schema: "turnierplan",
                table: "IAM_PlanningRealm",
                newName: "IX_IAM_PlanningRealm_PlanningRealmId");

            migrationBuilder.RenameColumn(
                name: "TournamentPlannerId",
                schema: "turnierplan",
                table: "Applications",
                newName: "PlanningRealmId");

            migrationBuilder.RenameIndex(
                name: "IX_Applications_TournamentPlannerId",
                schema: "turnierplan",
                table: "Applications",
                newName: "IX_Applications_PlanningRealmId");

            migrationBuilder.AddForeignKey(
                name: "FK_Applications_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "Applications",
                column: "PlanningRealmId",
                principalSchema: "turnierplan",
                principalTable: "PlanningRealms",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_IAM_PlanningRealm_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "IAM_PlanningRealm",
                column: "PlanningRealmId",
                principalSchema: "turnierplan",
                principalTable: "PlanningRealms",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_InvitationLinks_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "InvitationLinks",
                column: "PlanningRealmId",
                principalSchema: "turnierplan",
                principalTable: "PlanningRealms",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Labels_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "Labels",
                column: "PlanningRealmId",
                principalSchema: "turnierplan",
                principalTable: "PlanningRealms",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TournamentClasses_PlanningRealms_PlanningRealmId",
                schema: "turnierplan",
                table: "TournamentClasses",
                column: "PlanningRealmId",
                principalSchema: "turnierplan",
                principalTable: "PlanningRealms",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
