on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: 'Build & Test'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Setup .NET SDK 10.x'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.x'
      - name: 'Setup Node.js 24.x'
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - name: 'Setup Chrome'
        uses: browser-actions/setup-chrome@v1
        id: 'setup-chrome'
      - name: 'Set CHROME_BIN environment variable'
        run: 'echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $env:GITHUB_ENV'
      - name: 'Restore .NET solution'
        run: 'dotnet restore'
        working-directory: './src'
      - name: 'Build .NET solution'
        run: 'dotnet build --no-restore -c Release'
        working-directory: './src'
      - name: 'Test .NET solution'
        run: 'dotnet test --no-build -c Release'
        working-directory: './src'
      - name: 'Install npm packages'
        run: 'npm ci'
        working-directory: './src/Turnierplan.App/Client/'
      - name: 'Build client application'
        run: 'npm run build:prod'
        working-directory: './src/Turnierplan.App/Client/'
      - name: 'Lint client application'
        run: 'npm run lint:ci'
        working-directory: './src/Turnierplan.App/Client/'
      - name: 'Test client application'
        run: 'npm run test:ci'
        working-directory: './src/Turnierplan.App/Client/'

  e2e-amd64:
    name: 'E2E Tests (amd64)'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Setup Node.js 24.x'
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - name: 'Install npm packages'
        run: 'npm ci'
        working-directory: './src/Turnierplan.App/Client/'
      - name: 'Prepare e2e test environment'
        run: 'npm run e2e:prepare:amd64'
        working-directory: './src/Turnierplan.App/Client/'
      - name: 'Run e2e tests'
        run: 'npm run e2e:run'
        working-directory: './src/Turnierplan.App/Client/'
      - name: 'Destroy e2e test environment'
        run: 'npm run e2e:destroy'
        working-directory: './src/Turnierplan.App/Client/'
